# A list of HTML tags in no particular order. It's not complete.
tags = {
    :html=>true,
    :head=>true,
    :body=>true,
    :title=>true,
    :p=>true,
    :div=>true,
    :span=>true,
    :span=>true,
    :font=>true,
    :b=>true,
    :i=>true,
    :tt=>true,
    :h1=>true,
    :h2=>true,
    :h3=>true,
    :h4=>true,
    :h5=>true,
    :h6=>true,
    :form=>true,
    :button=>true,
    :base=>true,
    :em=>true,
    :strong=>true,
    :dfn=>true,
    :code=>true,
    :samp=>true,
    :kbd=>true,
    :var=>true,
    :cite=>true,
    :del=>true,
    :ins=>true,
    :applet=>true,
    :object=>true,
    :menu=>true,
    :table=>true,
    :pre=>true,
    :col=>true,
    :area=>true,

    :img=>false,
    :br=>false,
    :link=>false,
    :hr=>false
}

tags.each {|tag, paired|
  Rubified.new_tag(tag, paired)
}